
[tasks.deploy]
script = [
    "cp -r zhongchar-deploy/.git /tmp",
    "toml set Trunk.toml build.public_url ./ > temp.toml",
    "mv temp.toml Trunk.toml",
    "sed -i 's|<meta name=\"domain-path\" content=.*|<meta name=\"domain-path\" content=\"/zhongchar-deploy/\"/>|' index.html",
    "trunk build --release -d zhongchar-deploy",
    "cp -r /tmp/.git zhongchar-deploy",
]

[tasks.run]
script = [
    "toml set Trunk.toml build.public_url / > temp.toml",
    "mv temp.toml Trunk.toml",
    "sed -i 's|<meta name=\"domain-path\" content=.*|<meta name=\"domain-path\" content=\"/\"/>|' index.html",
    "trunk serve --open",
]
